# Generated by Django 5.1.4 on 2024-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='guests',
            new_name='kids',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='message',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='partner',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
