name: Build CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      DROPZONE_URL: "https://google.com"
    
    steps:
    - uses: actions/checkout@v4
    - name: Create .env
      run: |
        touch .env
        echo "SECRET_KEY=${SECRET_KEY}" >> .env
        echo "DEBUG=False" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
        echo "DROPZONE_URL=https://google.com" >> .env
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Run docker-compose
      run: docker compose up --build -d
    - name: ls Container
      run: docker compose ps -a
    #   no Migrate since not needed in this use case